database:
  restart: always
  image: sameersbn/postgresql:10-2
  environment:
    - PG_TRUST_LOCALNET=true
    - DB_NAME=luiza
    - DB_USER=admin
    - DB_PASS=admin
    - PG_RUNDIR=/run/postgres
    - PG_LOGDIR=/var/log/postgres
  ports:
    - "5432:5432"
  volumes:
    - data:/var/lib/postgresql
    - logs:/var/log/postgresql