spring:
  datasource:
    url: #
    username: #
    password: #

  jpa:
    hibernate:
      ddl-auto: #
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
